### ISSUE TITLE
阿里云-移动推送 SDK

### ISSUE THREAD

**Issue by wenjiasen** [aliyun/aliyun-openapi-nodejs-sdk#1]
从https://github.com/aliyun-UED/aliyun-sdk-js 导航过来的，请问可以提供移动推送Node.js相关的SDK么？

**Comment by JacksonTian** [comment]
可以。能否发一下移动推送的文档地址，我好确定名字和版本号。

**Comment by JacksonTian** [comment]
亲，模块已经发布到 npm 了。

**Comment by JacksonTian** [comment]
抱歉没有生成文档，不过你可以看一下源码 https://github.com/aliyun/push-2016-08-01/blob/master/lib/client.js 应该就知道怎么用了。

**Comment by JacksonTian** [comment]
```
+ @alicloud/push-2016-08-01@1.0.0
```

模块名及版本如上。

**Comment by wenjiasen** [comment]
@JacksonTian  你发的源码链接404额

**Comment by JacksonTian** [comment]
仓库名字被我rename 了。用新地址吧 https://github.com/aliyun/aliyun-openapi-nodejs-sdk/blob/master/Push-2016-08-01/lib/client.js
