### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by poelstra** [aliyun/aliyun-openapi-nodejs-sdk#17]
We're using TypeScript in our project, and it would be very convenient if these API's have corresponding TypeScript typings.

I noticed that @alicloud/pop-core already has typings.

It seems these SDKs are auto-generated. Would it be possible to also emit *.d.ts files for each of them?

**Comment by JacksonTian** [comment]
Hi @poelstra , your requirement is make sense. We will support it asap. Thank you.

**Comment by JacksonTian** [comment]
You can use https://next.api.aliyun.com/ to use typescript-version SDK directly now.
