### ISSUE TITLE
需要 RAM, ECS, OSS, SLB, RDS 等核心产品的 SDK

### ISSUE THREAD

**Issue by changkun** [aliyun/aliyun-openapi-nodejs-sdk#3]
请问可以尽快编译这部分 SDK 吗?

**Comment by changkun** [comment]
@JacksonTian 
RAM: https://www.alibabacloud.com/help/zh/doc-detail/62184.htm?spm=a2c63.l28256.b99.52.5f2d7d30wK32pb
ECS: https://www.alibabacloud.com/help/zh/doc-detail/25485.htm?spm=a2c63.p38356.b99.233.ec7e47174lcjQr
OSS: https://www.alibabacloud.com/help/zh/doc-detail/31948.htm?spm=a2c63.l28256.b99.311.3e125cc5lwzinc
SLB: https://www.alibabacloud.com/help/zh/doc-detail/27566.htm?spm=a2c63.l28256.b99.80.53462cc8QZuHyO
VPC: https://www.alibabacloud.com/help/zh/doc-detail/35479.htm?spm=a2c63.l28256.b99.38.52ca4b66WqH7yu
RDS: https://www.alibabacloud.com/help/zh/doc-detail/26226.htm?spm=a2c63.l28256.b99.240.7edb653c7cPRxE
MongoDB: https://www.alibabacloud.com/help/zh/doc-detail/61715.htm?spm=a2c63.l28256.b99.99.7d64255dE4li8e
容器: https://www.alibabacloud.com/help/zh/doc-detail/26044.htm?spm=a2c63.l28256.b99.359.783e2fd0rAcumY
资源编排： https://www.alibabacloud.com/help/zh/doc-detail/28899.htm?spm=a2c63.l28256.b99.31.40ee41dcBHy0mZ

**Comment by JacksonTian** [comment]
收到。

**Comment by JacksonTian** [comment]
OSS 不是一个标准的 POP，请使用 https://github.com/ali-sdk/ali-oss

**Comment by JacksonTian** [comment]
除了 Vpc/ECS 及 OSS 之外的 SDK 都已经生成完毕，稍后更新文档。

**Comment by JacksonTian** [comment]
文档更新完毕，如果对参数有什么问题，请参见一下官方的 API 文档。

**Comment by JacksonTian** [comment]
ECS 和 VPC 暂时遇到一点问题，待解决。
