### ISSUE TITLE
需要VOD(视频点播服务)SDK

### ISSUE THREAD

**Issue by jerrwy** [aliyun/aliyun-openapi-nodejs-sdk#4]

**Comment by JacksonTian** [comment]
请发我一下该产品的 OpenAPI/SDK 文档。

**Comment by jerrwy** [comment]
> 请发我一下该产品的 OpenAPI/SDK 文档。

https://help.aliyun.com/product/29932.html

**Comment by JacksonTian** [comment]
该产品已经发布了。@alicloud/vod-2017-03-21
