### ISSUE TITLE
请发布最新版本的 IoT API 

### ISSUE THREAD

**Issue by xueshibing** [aliyun/aliyun-openapi-nodejs-sdk#7]
现在最新版本是 ： 2018-01-20

**Comment by JacksonTian** [comment]
请给一下 API 文档链接 我确认下。

**Comment by xueshibing** [comment]
这里写了最新版本
https://help.aliyun.com/document_detail/30561.html  

API 文档
https://help.aliyun.com/document_detail/69893.html

**Comment by JacksonTian** [comment]
`+ @alicloud/iot-2018-01-20@1.0.0` done.
