### ISSUE TITLE
ecs的SDK不存在，希望能提供

### ISSUE THREAD

**Issue by sailwebs** [aliyun/aliyun-openapi-nodejs-sdk#8]

**Comment by JacksonTian** [comment]
https://github.com/aliyun/aliyun-openapi-nodejs-sdk/tree/master/Ecs-2014-05-26 这个就是。

**Comment by coderafei** [comment]
https://www.npmjs.com/search?q=%40alicloud%2Fecs-2014-05-26
不存在的，新版本npm上也没有

**Comment by JacksonTian** [comment]
@alicloud/ecs-2014-05-26@1.0.0 发布了。
